### ISSUE TITLE
Никак не могу преодолеть ошибку

### ISSUE THREAD

**Issue by dmitrygadeev** [MamontenKa/YMS#3]
`Traceback (most recent call last):
  File "downloader.py", line 195, in <module>
    yandex.auth()
  File "downloader.py", line 46, in auth
    csrf_token, process_uuid = self.find_auth_data(auth_page)
  File "downloader.py", line 172, in find_auth_data
    csrf_token = html[csrf_token.start():csrf_token.end()][11:-1]
AttributeError: 'NoneType' object has no attribute 'start'`

**Comment by inaryzhnyy** [comment]
Я так смог токен получить 
csrf_token = re.search('"csrf":".*?"', html)
csrf_token = html[csrf_token.start():csrf_token.end()][8:-1]
